name: Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Vercel CLI Globally
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=$VERCEL_ACCESS_TOKEN
      - name: Build Project Artifacts
        run: vercel build --token=$VERCEL_ACCESS_TOKEN
      - name: Confirm the presence of dist folder
        # skip displaying the node_modules folder entirely in tree view
        run: tree -I 'node_modules'
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=$VERCEL_ACCESS_TOKEN
