name: Build and Deploy
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Verify Node Version
        run: node -v
      - name: Install node_modules
        run: npm install
      - name: Verify Vercel CLI Version
        run: vercel --version
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=$VERCEL_ACCESS_TOKEN
      - name: Build Project Attributes
        run: vercel build --prod --token=$VERCEL_ACCESS_TOKEN
      - name: Confirm the presence of dist folder
        #run: ls -la
        run: ls -la dist

  deploy-app:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Action
        uses: actions/checkout@v4
      - name: Download the dist folder
        uses: actions/download-artifact@v4
        with:
          name: built
          path: dist
      - name: Confirm build/dist folder exists
        #run: ls -la
        run: ls -la dist
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=$VERCEL_ACCESS_TOKEN
