# this is an example test.yml file to learn about YAML and GitHub Actions
name: Learn CI/CD with GitHub Actions # workflow name
# on: [push] # runs this job on a commit push
on:
  push:
    branches:
      - main

# since each job is an object so they parallelly and not sequentially
jobs:
  print-hello-world:
    # uses latest ubuntu docker image
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello World!'

  print-hello-world-again:
    runs-on: ubuntu-latest # uses latest ubuntu docker image
    steps:
      - name: Print Hello World Again
        run: echo 'Hello World Again!'

  show-file-tree:
    runs-on: ubuntu-latest
    # since steps are an array so they run sequentially and not parallelly
    steps:
      # `actions/checkout@v4` action checks-out the repository under `$GITHUB_WORKSPACE`, so that the workflow can access it
      - uses: actions/checkout@v4
      # bash command to show the tree view of files in your react project
      - run: tree

  #deploy-app:
  #  needs: build-app
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Deploy Project Artifacts to Vercel
  #      run: vercel deploy --prod --token=$VERCEL_ACCESS_TOKEN
